---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /v1/admit
  failurePolicy: Ignore
  name: vpolicy.cedar.k8s.aws
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - configmaps
    - secrets
    - serviceaccounts
  sideEffects: None
  timeoutSeconds: 30