name: Cedar Validation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env: 
  CEDAR_VERSION: 4.2.1
jobs:
  cedar:
    name: Cedar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cedar-cli
        run: cargo install cedar-policy-cli@${{env.CEDAR_VERSION}}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{env.CEDAR_VERSION}}
      - name: Validate Policies
        run: make validate-policies
