name: Cedar Validation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  cedar:
    name: Cedar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Policies
        uses: common-fate/cedar-validate-action@v1
        with:
          schema-file: ./cedarschema/k8s-full.cedarschema.json
          policy-files: '**/*.cedar'